# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/nodejs/node/blob/main/BUILDING.md#windows
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: pythonPackage
      directives:
        description: Install Python 3.14
        module: Microsoft.WinGet.DSC
        allowPrerelease: true
      settings:
        id: Python.Python.3.14
        source: winget
    - resource: Microsoft.winGet.DSC/winGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Community
        allowPrerelease: true
        
